# Generated by Django 3.2.12 on 2022-03-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
