# Generated by Django 3.2.12 on 2022-03-17 23:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220317_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='checking_sub_account_balance',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='savings_sub_account_balance',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 23, 42, 36, 414697, tzinfo=utc)),
        ),
    ]
