# Generated by Django 3.2.12 on 2022-03-26 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220324_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 15, 51, 33, 778588, tzinfo=utc)),
        ),
    ]
