# Generated by Django 3.2.12 on 2022-04-08 00:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(default=0, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.TextField(verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 0, 24, 52, 529904, tzinfo=utc)),
        ),
    ]
