# Generated by Django 3.2.12 on 2022-03-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_rename_given_at_oauth2userconsent_status_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2client',
            name='grant_type',
            field=models.TextField(default='authorization_code'),
        ),
        migrations.AlterField(
            model_name='oauth2client',
            name='response_type',
            field=models.TextField(default='code'),
        ),
        migrations.AlterField(
            model_name='oauth2client',
            name='scope',
            field=models.TextField(default='accounts'),
        ),
        migrations.AlterField(
            model_name='oauth2client',
            name='token_endpoint_auth_method',
            field=models.CharField(default='none', editable=False, max_length=120),
        ),
    ]
