# Generated by Django 3.2.12 on 2022-03-17 01:09

from django.db import migrations, models
import oauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_alter_oauth2token_issued_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth2userconsent',
            name='is_authorized',
        ),
        migrations.AddField(
            model_name='oauth2userconsent',
            name='status',
            field=models.TextField(choices=[('AWAITING_AUTHORISATION', 'AWAITING_AUTHORISATION'), ('AUTHORISED', 'AUTHORISED')], default='AWAITING_AUTHORISATION'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='issued_at',
            field=models.IntegerField(default=oauth.models.now_timestamp),
        ),
        migrations.AlterField(
            model_name='oauth2userconsent',
            name='given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oauth2userconsent',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
