# Generated by Django 3.2.12 on 2022-03-17 02:07

from django.db import migrations, models
import oauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_auto_20220316_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2userconsent',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='issued_at',
            field=models.IntegerField(default=oauth.models.now_timestamp),
        ),
    ]
